[versions]
kotest = "6.0.5"
springdoc = "2.8.14"
springBoot = "3.5.8"
spotless = "8.1.0"
detekt = "1.23.8"
cyclonedx = "3.1.0"

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[libraries]
kotestAssertionsJson = { module = "io.kotest:kotest-assertions-json", version.ref = "kotest" }
springdocOpenapiStarterWebmvcUi = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }

plugin-cyclonedx = { module = "org.cyclonedx.bom:org.cyclonedx.bom.gradle.plugin", version.ref = "cyclonedx" }
plugin-detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
plugin-spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
plugin-springBoot = { module = "org.springframework.boot:spring-boot-gradle-plugin", version.ref = "springBoot" }
