[versions]
springdoc = "2.0.2"
springBoot = "3.0.1"
gradleKtlintPlugin = "11.0.0"
springDependencyManagementPlugin = "1.1.0"

[libraries]
springdocOpenapiStarterWebmvcUi = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }

plugin-springBoot = { module = "org.springframework.boot:spring-boot-gradle-plugin", version.ref = "springBoot" }
plugin-springDependencyManagement = { module = "io.spring.gradle:dependency-management-plugin", version.ref = "springDependencyManagementPlugin" }
plugin-ktlint = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "gradleKtlintPlugin" }
