name: "Docker Compose caching"

on:
  pull_request:

jobs:
  compose:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Start Docker compose
        run: docker compose up --build --wait

      - name: Stop Docker compose
        run: docker compose down
