name: Gradle

on:
  pull_request:
  workflow_dispatch:
  merge_group:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ "main" ]

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-22.04-arm
    name: "Build"
    permissions:
      id-token: write # for codecov
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: '0' # to allow sonar to attach git blame information
      - uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          distribution: "liberica"
          java-version: 21
      - uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - run: "./gradlew build --continue"
      - uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
        with:
          use_oidc: 'true'
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: "gradle-build-artifacts"
          path: |
            **/build/**
            !buildSrc/build/**

  integration:
    runs-on: ubuntu-22.04-arm
    name: "Integration test"
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          distribution: "liberica"
          java-version: 21
      - uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - run: "./gradlew integrationTest --continue --info"
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: "gradle-integration-artifacts"
          path: |
            **/build/**
            !buildSrc/build/**
