name: Gradle

on:
  pull_request:
  workflow_dispatch:
  merge_group:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ "main" ]

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-22.04-arm
    name: "Build"
    permissions:
      id-token: write # for codecov
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          fetch-depth: '0' # to allow sonar to attach git blame information
      - uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          distribution: "liberica"
          java-version: 21
      - uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - run: "./gradlew build --continue"
      - uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
        with:
          use_oidc: 'true'
      - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: "gradle-build-artifacts"
          path: |
            **/build/**
            !buildSrc/build/**

  integration:
    runs-on: ubuntu-22.04-arm
    name: "Integration test"
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          distribution: "liberica"
          java-version: 21
      - uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - run: docker compose -f docker-compose.yml --profile app up --wait --build
      - run: "./gradlew integrationTest --continue"
      - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: "gradle-integration-artifacts"
          path: |
            **/build/**
            !buildSrc/build/**
