name: Publish

on:
  pull_request:
  workflow_dispatch:
  merge_group:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ "main" ]
  release:
    types: [ published ]

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-22.04
    name: "Gradle"
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          distribution: "liberica"
          java-version: 21

      - uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - id: version
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "version=pr-${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          elif [ "${{ github.event_name }}" = "release" ]; then
            echo "version=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          elif [ "${{ github.event_name }}" = "push" ]; then
            echo "version=${{ github.ref_name }}-SNAPSHOT" >> $GITHUB_OUTPUT
          else
            echo "version=nightly-SNAPSHOT" >> $GITHUB_OUTPUT
          fi
          

      - run: "./gradlew publishToMavenLocal -Pversion=${{ steps.version.outputs.version }}"

      - if: github.event_name != 'pull_request' || github.event_name != 'merge_group'
        run: "./gradlew publish -Pversion=${{ steps.version.outputs.version }}"
        env:
          GPR_USERNAME: ${{ github.actor }}
          GPR_PASSWORD: ${{ github.token }}
