name: Gradle

on:
  pull_request:
  workflow_dispatch:
  merge_group:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ "main" ]

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-22.04-arm
    name: "Build"
    permissions:
      id-token: write # for codecov
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: '0' # to allow sonar to attach git blame information
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: "liberica"
          java-version: 25
      - uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - run: "./gradlew build --continue"
      - uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          use_oidc: 'true'
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: "gradle-build-artifacts"
          path: |
            **/build/**
            !buildSrc/build/**

  integration:
    runs-on: ubuntu-22.04-arm
    name: "Integration test"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: "liberica"
          java-version: 21
      - uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - run: docker compose -f docker-compose.yml --profile app up --wait --build
      - run: "./gradlew integrationTest --continue"
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: "gradle-integration-artifacts"
          path: |
            **/build/**
            !buildSrc/build/**
