name: Release

on:
  pull_request:
  merge_group:
  push:
    branches: [ main ]

permissions: read-all

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: release-token
        with:
          app-id: ${{ vars.RELEASE_APP_ID }}
          private-key: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}
          permission-contents: write # to be able to publish a GitHub release
          permission-issues: write # to be able to comment on released issues
          permission-pull-requests: write # to be able to comment on released pull requests

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ steps.release-token.outputs.token }}
          fetch-depth: 0
          sparse-checkout: release

      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          package_json_file: 'release/package.json'

      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: 'release/.nvmrc'
          cache: 'pnpm'
          cache-dependency-path: 'release/pnpm-lock.yaml'

      - run: pnpm install --frozen-lockfile
        working-directory: release

      - run: pnpm run release
        working-directory: release
        env:
          GH_TOKEN: ${{ steps.release-token.outputs.token }}
